// Generated variants of the current scorer with a different TRANSITION_MAX (data for choosing it).
// Copies src/game/scoring.ts + align.ts into qa/realism/out/variants/ with the constant replaced and
// imports re-pointed, then imports them. Regenerated on every run, so they always follow src/.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import type { AfterImpl } from './pipeline';
import { REPO_ROOT } from './scores';

const DIR = resolve(REPO_ROOT, 'qa/realism/out/variants');

export async function transitionMaxVariant(sec: number): Promise<AfterImpl> {
  mkdirSync(DIR, { recursive: true });
  const tag = `tm${Math.round(sec * 1000)}`;
  const src = (f: string) => readFileSync(resolve(REPO_ROOT, 'src/game', f), 'utf8');
  const repoint = (code: string) => code
    .replace(/from '\.\.\/music\//g, "from '../../../../src/music/")
    .replace(/from '\.\/types'/g, "from '../../../../src/game/types'")
    .replace(/from '\.\/analysis'/g, "from '../../../../src/game/analysis'");
  let scoring = repoint(src('scoring.ts'));
  const re = /export const TRANSITION_MAX = [0-9.]+;/;
  if (!re.test(scoring)) throw new Error('TRANSITION_MAX not found in src/game/scoring.ts');
  scoring = scoring.replace(re, `export const TRANSITION_MAX = ${sec};`);
  const align = repoint(src('align.ts')).replace(/from '\.\/scoring'/g, `from './scoring-${tag}'`);
  writeFileSync(resolve(DIR, `scoring-${tag}.ts`), `// GENERATED by qa/realism/variants.ts — do not edit.\n${scoring}`);
  writeFileSync(resolve(DIR, `align-${tag}.ts`), `// GENERATED by qa/realism/variants.ts — do not edit.\n${align}`);
  const s = await import(/* @vite-ignore */ resolve(DIR, `scoring-${tag}.ts`));
  const a = await import(/* @vite-ignore */ resolve(DIR, `align-${tag}.ts`));
  return { scoreAttempt: s.scoreAttempt, scoreAligned: a.scoreAligned, medianOnsetMs: a.medianOnsetMs };
}
